-- public.is_admin() has existed since 002_admin_hardening.sql, but was only
-- ever called from inside RLS policy expressions until requireAdmin
-- (server/utils/admin-guard.ts) started calling it directly via .rpc().
-- 004_roles_and_capabilities.sql explicitly granted execute on
-- has_capability()/my_capabilities() to authenticated, precisely because a
-- client calls those directly too — this migration closes the same gap for
-- is_admin(), which 002 missed because nothing called it directly back
-- then. Depending on a project's default privilege configuration, a
-- missing grant here can make every requireAdmin-gated route 403 an actual
-- admin, indistinguishable from "not an admin" without reading server logs.
grant execute on function public.is_admin() to authenticated;
