-- Supabase Schema SQL
-- Settings
--- Create enum type for settings
do $$
begin
  if not exists (select 1 from pg_type where typname = 'tsettings') then
    create type TSettings as enum (
      'website_title',
      'website_url',
      'website_description'
    );
  end if;
end
$$;

--- Create settings table
create table public.settings (
  id bigint generated by default as identity not null,
  setting_name public.TSettings not null,
  setting_value text not null,
  constraint settings_pkey primary key (id),
  constraint settings_setting_name_key unique (setting_name)
) TABLESPACE pg_default;

--- Insert default settings (website_title, website_url, website_description)
insert into public.settings (setting_name, setting_value) values
('website_title', 'My Website'),
('website_url', 'https://mywebsite.test'),
('website_description', 'This is my website.');

alter table public.settings enable row level security;

-- Policies for settings table
create policy "Enable insert for authenticated users only"
on public.settings
to authenticated, dashboard_user
with check (true);

-- Profiles
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  first_name text,
  last_name text,
  constraint first_name_length check (char_length(first_name) >= 3)
);

alter table public.profiles enable row level security;

--- inserts a row into public.profiles
create function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, first_name, last_name)
  values (new.id, new.raw_user_meta_data ->> 'first_name', new.raw_user_meta_data ->> 'last_name');
  return new;
end;
$$;
--- trigger the function every time a user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
