-- Settings
create table public.settings (
  id bigint generated by default as identity not null,
  setting_name public.Settings not null,
  setting_value text not null,
  constraint settings_pkey primary key (id),
  constraint settings_setting_name_key unique (setting_name)
) TABLESPACE pg_default;

--- Insert default settings (website_title, website_url, website_description)
insert into public.settings (setting_name, setting_value) values
('website_title', null),
('website_url', null),
('website_description', null);

alter policy "Enable insert for authenticated users only"
on "public"."settings"
to authenticated, dashboard_user
with check (true);

alter policy "Enable read access for all users"
on "public"."settings"
to authenticated, dashboard_user
using (true);

alter policy "Policy with table joins"
on "public"."settings"
to authenticated, dashboard_user
using (true);

-- Profiles
create table public.profiles (
  id uuid not null references auth.users on delete cascade,
  first_name text,
  last_name text,
  primary key (id)
);

alter table public.profiles enable row level security;

--- inserts a row into public.profiles
create function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, first_name, last_name)
  values (new.id, new.raw_user_meta_data ->> 'first_name', new.raw_user_meta_data ->> 'last_name');
  return new;
end;
$$;
--- trigger the function every time a user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
