-- Supabase Schema SQL

-- Profiles
--
-- Created first, ahead of settings/healthcheck, because those tables'
-- policies call public.is_admin() below, which queries this table. Postgres
-- resolves function references at CREATE POLICY time, so is_admin() (and
-- the table it reads) must already exist before any policy uses it.
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  email text,
  username text,
  display_name text,
  is_admin boolean not null default false,
  constraint username_length check (char_length(username) >= 3)
);

alter table public.profiles enable row level security;

-- Returns true when the calling user's own profile has is_admin = true.
-- SECURITY DEFINER so this lookup runs with the function owner's
-- privileges rather than the caller's — RLS policies call this to decide
-- whether to grant a *wider* read/write than a user's own row would
-- otherwise get, so the check itself must not be subject to those same
-- policies.
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = ''
stable
as $$
  select coalesce(
    (select is_admin from public.profiles where id = auth.uid()),
    false
  );
$$;

-- A user can always read their own profile; only admins can read
-- everyone's. Previously any authenticated user could read every row
-- (including every user's email) — this was the actual reason `is_admin`
-- existed on the table but no policy referenced it.
drop policy if exists "Enable read access for authenticated users" on public.profiles;

create policy "Enable read access for authenticated users"
on public.profiles
for select
to authenticated, dashboard_user
using (auth.uid() = id or public.is_admin());

-- Settings
--- Create enum type for settings
do $$
begin
  if not exists (select 1 from pg_type where typname = 'tsettings') then
    create type TSettings as enum (
      'website_title',
      'website_url',
      'website_description'
    );
  end if;
end
$$;

--- Create settings table
create table if not exists public.settings (
  id bigint generated by default as identity not null,
  setting_name public.TSettings not null,
  setting_value text not null,
  constraint settings_pkey primary key (id),
  constraint settings_setting_name_key unique (setting_name)
) TABLESPACE pg_default;

--- Insert default settings (website_title, website_url, website_description)
insert into public.settings (setting_name, setting_value) values
('website_title', 'My Website'),
('website_url', 'https://mywebsite.test'),
('website_description', 'This is my website.')
on conflict (setting_name) do nothing;

alter table public.settings enable row level security;

-- Reading settings (site title/url/description) is not sensitive, so any
-- authenticated user may read them — the admin navbar and settings page
-- both fetch this for whoever is logged in, not only admins. Only writes
-- are admin-gated.
do $$
begin
  if not exists (
    select 1 from pg_policies where tablename = 'settings' and policyname = 'Enable read access for authenticated users on settings'
  ) then
    create policy "Enable read access for authenticated users on settings"
    on public.settings
    for select
    to authenticated, dashboard_user
    using (true);
  end if;
end
$$;

-- Previously any authenticated user (not just an admin) could insert or
-- update settings — see server/api/settings/update.post.ts, which also
-- now requires an admin session.
drop policy if exists "Enable insert for authenticated users only" on public.settings;

create policy "Enable insert for authenticated users only"
on public.settings
for insert
to authenticated, dashboard_user
with check (public.is_admin());

drop policy if exists "Enable update for authenticated users on settings" on public.settings;

create policy "Enable update for authenticated users on settings"
on public.settings
for update
to authenticated, dashboard_user
using (public.is_admin())
with check (public.is_admin());

--- Create enum type for healthcheck names
do $$
begin
  if not exists (select 1 from pg_type where typname = 'thealthcheck') then
    create type THealthcheck as enum (
      'first_setup'
    );
  end if;
end
$$;

--- Create healthcheck table (name/value format like settings)
create table if not exists public.healthcheck (
  id bigint generated by default as identity not null,
  config_name public.THealthcheck not null,
  config_value text not null,
  constraint healthcheck_pkey primary key (id),
  constraint healthcheck_config_name_key unique (config_name)
) TABLESPACE pg_default;

--- Insert default healthcheck values
insert into public.healthcheck (config_name, config_value) values
('first_setup', 'true')
on conflict (config_name) do nothing;

alter table public.healthcheck enable row level security;

-- Allow read access to healthcheck for public and dashboard_user (no login required)
do $$
begin
  if not exists (
    select 1 from pg_policies where tablename = 'healthcheck' and policyname = 'Enable read access for healthcheck to public'
  ) then
    create policy "Enable read access for healthcheck to public"
    on public.healthcheck
    for select
    to public
    using (true);
  end if;
end
$$;

-- Previously any authenticated user (not just an admin) could flip
-- first_setup back to 'true', which would re-open the unauthenticated
-- setup wizard for every visitor.
drop policy if exists "Enable update for authenticated users on healthcheck" on public.healthcheck;

create policy "Enable update for authenticated users on healthcheck"
on public.healthcheck
for update
to authenticated, dashboard_user
using (public.is_admin())
with check (public.is_admin());

--- inserts a row into public.profiles
--- automatically grants admin to the first user if no profiles exist yet
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
declare
  profile_count int;
  should_be_admin boolean;
begin
  select count(*) into profile_count from public.profiles;

  -- Only the very first account is auto-promoted. Never trust
  -- raw_user_meta_data for this: it is fully client-controlled — anyone can
  -- pass an arbitrary `options.data` straight to Supabase's own
  -- /auth/v1/signup endpoint, bypassing this project's own /api/auth/signup
  -- route entirely — so honoring an `is_admin` key there let any new
  -- signup grant itself admin.
  should_be_admin := profile_count = 0;

  insert into public.profiles (id, email, username, display_name, is_admin)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data ->> 'username',
    new.raw_user_meta_data ->> 'display_name',
    should_be_admin
  );
  return new;
end;
$$;
--- trigger the function every time a user is created
do $$
begin
  if not exists (
    select 1 from pg_trigger where tgname = 'on_auth_user_created'
  ) then
    create trigger on_auth_user_created
      after insert on auth.users
      for each row execute procedure public.handle_new_user();
  end if;
end
$$;

-- Migrations tracking
create table if not exists public.pluto_migrations (
  id bigint generated by default as identity primary key,
  layer_name text not null,
  applied_at timestamptz not null default now(),
  constraint pluto_migrations_layer_key unique (layer_name)
);

alter table public.pluto_migrations enable row level security;

-- Only authenticated users can read migrations
do $$
begin
  if not exists (
    select 1 from pg_policies where tablename = 'pluto_migrations' and policyname = 'Enable read access for authenticated users on pluto_migrations'
  ) then
    create policy "Enable read access for authenticated users on pluto_migrations"
    on public.pluto_migrations
    for select
    to authenticated, dashboard_user
    using (true);
  end if;
end
$$;
