-- Supabase Schema SQL
-- Settings
--- Create enum type for settings
do $$
begin
  if not exists (select 1 from pg_type where typname = 'tsettings') then
    create type TSettings as enum (
      'website_title',
      'website_url',
      'website_description'
    );
  end if;
end
$$;

--- Create settings table
create table if not exists public.settings (
  id bigint generated by default as identity not null,
  setting_name public.TSettings not null,
  setting_value text not null,
  constraint settings_pkey primary key (id),
  constraint settings_setting_name_key unique (setting_name)
) TABLESPACE pg_default;

--- Insert default settings (website_title, website_url, website_description)
insert into public.settings (setting_name, setting_value) values
('website_title', 'My Website'),
('website_url', 'https://mywebsite.test'),
('website_description', 'This is my website.')
on conflict (setting_name) do nothing;

alter table public.settings enable row level security;

-- Policies for settings table
do $$
begin
  if not exists (
    select 1 from pg_policies where tablename = 'settings' and policyname = 'Enable insert for authenticated users only'
  ) then
    create policy "Enable insert for authenticated users only"
    on public.settings
    for insert
    to authenticated, dashboard_user
    with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies where tablename = 'settings' and policyname = 'Enable read access for authenticated users on settings'
  ) then
    create policy "Enable read access for authenticated users on settings"
    on public.settings
    for select
    to authenticated, dashboard_user
    using (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies where tablename = 'settings' and policyname = 'Enable update for authenticated users on settings'
  ) then
    create policy "Enable update for authenticated users on settings"
    on public.settings
    for update
    to authenticated, dashboard_user
    using (true)
    with check (true);
  end if;
end
$$;

--- Create enum type for healthcheck names
do $$
begin
  if not exists (select 1 from pg_type where typname = 'thealthcheck') then
    create type THealthcheck as enum (
      'first_setup'
    );
  end if;
end
$$;

--- Create healthcheck table (name/value format like settings)
create table if not exists public.healthcheck (
  id bigint generated by default as identity not null,
  config_name public.THealthcheck not null,
  config_value text not null,
  constraint healthcheck_pkey primary key (id),
  constraint healthcheck_config_name_key unique (config_name)
) TABLESPACE pg_default;

--- Insert default healthcheck values
insert into public.healthcheck (config_name, config_value) values
('first_setup', 'true')
on conflict (config_name) do nothing;

alter table public.healthcheck enable row level security;

-- Allow read access to healthcheck for public and dashboard_user (no login required)
do $$
begin
  if not exists (
    select 1 from pg_policies where tablename = 'healthcheck' and policyname = 'Enable read access for healthcheck to public and dashboard_user'
  ) then
    create policy "Enable read access for healthcheck to public and dashboard_user"
    on public.healthcheck
    for select
    to public, dashboard_user
    using (true);
  end if;
end
$$;

-- Allow update access to healthcheck for authenticated users and dashboard_user
do $$
begin
  if not exists (
    select 1 from pg_policies where tablename = 'healthcheck' and policyname = 'Enable update for authenticated users on healthcheck'
  ) then
    create policy "Enable update for authenticated users on healthcheck"
    on public.healthcheck
    for update
    to authenticated, dashboard_user
    using (true)
    with check (true);
  end if;
end
$$;

-- Profiles
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  username text,
  display_name text,
  is_admin boolean not null default false,
  constraint username_length check (char_length(username) >= 3)
);

alter table public.profiles enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where tablename = 'profiles' and policyname = 'Enable read access for authenticated users'
  ) then
    create policy "Enable read access for authenticated users"
    on public.profiles
    for select
    to authenticated, dashboard_user
    using (true);
  end if;
end
$$;

--- inserts a row into public.profiles
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, username, display_name)
  values (new.id, new.raw_user_meta_data ->> 'username', new.raw_user_meta_data ->> 'display_name');
  return new;
end;
$$;
--- trigger the function every time a user is created
do $$
begin
  if not exists (
    select 1 from pg_trigger where tgname = 'on_auth_user_created'
  ) then
    create trigger on_auth_user_created
      after insert on auth.users
      for each row execute procedure public.handle_new_user();
  end if;
end
$$;
