import type postgres from 'postgres'
import { splitStatements } from './sql'

/**
 * Cheap check for whether `public.pluto_migrations` is already in the
 * target shape (has a `migration_name` column). Running this first, and
 * skipping every DDL statement below when it already passes, avoids
 * taking a DDL lock on the table on every server boot once a database has
 * already been upgraded.
 */
const PROBE_SQL = `
  select 1
  from information_schema.columns
  where table_schema = 'public'
    and table_name = 'pluto_migrations'
    and column_name = 'migration_name'
`

/**
 * Brings `public.pluto_migrations` from either shape (none yet, or the old
 * one-row-per-layer shape) to the versioned, per-migration shape:
 *
 * ```sql
 * create table if not exists public.pluto_migrations (
 *   id bigint generated by default as identity primary key,
 *   layer_name text not null,
 *   migration_name text not null,
 *   checksum text,
 *   applied_at timestamptz not null default now(),
 *   constraint pluto_migrations_layer_migration_key unique (layer_name, migration_name)
 * );
 * ```
 *
 * The backfill below (`migration_name = '001_baseline.sql'` for a null
 * row) is safe and correct because an old-shape row can only exist if the
 * old engine ran a layer's single monolithic schema file — that file is,
 * by construction, `001_baseline.sql` for every layer (see
 * `db/migrations/001_baseline.sql` for `core`, and the equivalent file in
 * every converted layer).
 */
export const ledgerDdl = `
create table if not exists public.pluto_migrations (
  id bigint generated by default as identity primary key,
  layer_name text not null,
  migration_name text not null,
  checksum text,
  applied_at timestamptz not null default now(),
  constraint pluto_migrations_layer_migration_key unique (layer_name, migration_name)
);

alter table public.pluto_migrations add column if not exists migration_name text;

alter table public.pluto_migrations add column if not exists checksum text;

update public.pluto_migrations set migration_name = '001_baseline.sql' where migration_name is null;

alter table public.pluto_migrations alter column migration_name set not null;

alter table public.pluto_migrations drop constraint if exists pluto_migrations_layer_key;

do $$
begin
  if not exists (
    select 1 from pg_constraint
     where conname = 'pluto_migrations_layer_migration_key'
       and conrelid = 'public.pluto_migrations'::regclass
  ) then
    alter table public.pluto_migrations
      add constraint pluto_migrations_layer_migration_key unique (layer_name, migration_name);
  end if;
end
$$;

alter table public.pluto_migrations enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where tablename = 'pluto_migrations' and policyname = 'Enable read access for authenticated users on pluto_migrations'
  ) then
    create policy "Enable read access for authenticated users on pluto_migrations"
    on public.pluto_migrations
    for select
    to authenticated, dashboard_user
    using (true);
  end if;
end
$$;
`

async function runLedgerSteps(
  tx: postgres.Sql | postgres.TransactionSql
): Promise<void> {
  const probe = await tx.unsafe(PROBE_SQL)

  if (probe.length > 0) {
    // Already in the target shape. Skip all DDL below.
    return
  }

  for (const statement of splitStatements(ledgerDdl)) {
    await tx.unsafe(statement)
  }
}

/**
 * Ensures `public.pluto_migrations` is in the versioned, per-migration
 * shape, running every DDL step in one transaction.
 *
 * Accepts either a plain connection or a connection already inside a
 * transaction. A plain connection (it has `.begin`) opens its own
 * transaction here; a connection already inside a transaction runs the
 * same steps directly, since the caller's transaction already wraps them.
 */
export async function ensureLedger(
  sql: postgres.Sql | postgres.TransactionSql
): Promise<void> {
  if (typeof (sql as postgres.Sql).begin === 'function') {
    await (sql as postgres.Sql).begin((tx) => runLedgerSteps(tx))
    return
  }

  await runLedgerSteps(sql as postgres.TransactionSql)
}
